name: Daily GM Bot

on:
  schedule:
    # Jalan setiap jam 00:00 UTC (07:00 WIB)
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  post-gm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
           npm config set @jsr:registry=https://npm.jsr.io
           npm install

      - name: Run Bot
        env:
          NOSTR_SK: ${{ secrets.NOSTR_SK }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: node bot.js
