name: Daily GM Bot

on:
  schedule:
    - cron: '0 0 * * *' # Setiap jam 07:00 WIB
  workflow_dispatch: # Supaya bisa klik tombol "Run" manual

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Paksa pakai Node 22 agar kompatibel dengan @google/genai

      - name: Install Dependencies
        run: |
          npm config set @jsr:registry=https://npm.jsr.io
          npm install

      - name: Run Bot
        env:
          NOSTR_SK: ${{ secrets.NOSTR_SK }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: node bot.mjs